Memory.creepRoles = {
  harvester: {
    currentAmount: 0,
    maxAmount: [3, 3, 3, 3, 3, 3, 3, 3],
    bodyParts: [
      [WORK, CARRY, MOVE],
      [WORK, CARRY, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    ],
    cost: 0
  },
  builder: {
    currentAmount: 0,
    maxAmount: [0, 4, 2, 2, 2, 2, 2, 2],
    bodyParts: [
      [WORK, CARRY, MOVE],
      [WORK, CARRY, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    ],
    cost: 0
  },
  upgrader: {
    currentAmount: 0,
    maxAmount: [3, 4, 3, 3, 3, 3, 3, 3],
    bodyParts: [
      [WORK, CARRY, MOVE],
      [WORK, CARRY, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
      [WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    ],
    cost: 0
  }
};

Memory.showActions;
